### ISSUE TITLE
Question: Is this working on new circleci windows executor?

### ISSUE THREAD

**Issue by ty-dev** [node-hid/node-hid#355]

**Comment by todbot** [comment]
I've no clue what that is. Could you reference an existing example?

**Comment by ty-dev** [comment]
CircleCI Windows Executor: https://circleci.com/docs/2.0/hello-world-windows/

Appears it was a electron + node-hid on windows combination when using electron-rebuild. Closing ticket but if it helps anyone in the future, need to  use vs2105 environment to get things working:
```
# .circleci/config.yml
version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: nvm install 8.10.0
      - run: nvm use 8.10.0
      - run: node -v
      - run: npm install --global --production windows-build-tools --vs2015
      - run: npm install node-gyp
      - run: npm install node-gyp -g
      # other build steps

```
